apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
  namespace: dhruv
spec:
  selector:
    app: simple-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
